In [5]:
from collections import ChainMap

test_dict1 = {"kleur": "rood", "user": "olijf"}
test_dict2 = {"kleur": "blauw"}

test_map = ChainMap(test_dict2, test_dict1)
print(test_map["kleur"])
print(test_map["user"])

blauw
olijf


In [1]:
from chemtools import chemdict
import numpy as np
import sympy

reactants = ["C2H6", "O2"]
products = ["CO2"]

react_dict_list = [chemdict(r) for r in reactants]
prod_dict_list = [chemdict(p) for p in products]

elements = {key for d in (react_dict_list + prod_dict_list) for key in d}
elements_dict = {el: i for i, el in enumerate(elements)}
print(f"elements_dict: {elements_dict}")

react_vectors = []
prod_vectors = []

for react in react_dict_list:
    vector = np.zeros(len(elements_dict))
    for k, v in react.items():
        vector[elements_dict[k]] = v
    react_vectors.append(vector)

for prod in prod_dict_list:
    vector = np.zeros(len(elements_dict))
    for k, v in prod.items():
        v *= -1
        vector[elements_dict[k]] = v
    prod_vectors.append(vector)

matrix = np.array(react_vectors + prod_vectors, dtype= "i")
matrix = matrix.T
print(matrix)
if not sympy.Matrix(matrix).nullspace():
    print("Not solvable")
    pass
ns_list = sympy.Matrix(matrix).nullspace()
print(ns_list)
#ns_list = ns_list * (1 / ns_list[0])
#print(list(ns_list))

elements_dict: {'C': 0, 'H': 1, 'O': 2}
[[ 2  0 -1]
 [ 6  0  0]
 [ 0  2 -2]]
Not solvable
[]


In [ ]:

if ns_list:
    ns = ns_list[0]
    print(f"Nullspace: {ns_list}")
    scalar, v_init = ns.as_content_primitive()
    print(f"Scalar {scalar}\nV: {v_init}")
    print("")
    answer = np.array(v_init).astype(int).flatten()
    print(answer.shape)

print(f"Answer: {answer}")

#factor = 1 / ns_list[0]
#print(ns_list * factor)

In [ ]:

all_compounds = [chemdict(c) for c in (reactants + products)]
element_dict = {el: i for d in all_compounds for i, el in enumerate(d)}
print(all_compounds[0] | all_compounds[1] | all_compounds[2])
print(all_compounds)
print(element_dict, "\n")

"""
vectoriseer
elementen = sorted({el for d in all_compounds for el in d})
"""


In [21]:

react_vectors = []
prod_vectors = []

for react in react_dict_list:
    print(react)
    vector = np.zeros(len(element_dict))
    test = list(([element_dict[k] ,v] for k ,v in react.items()))
    print(test)
    for i in test:
        a, b = i
        vector[a] = b
    react_vectors.append(vector)
print(react_vectors)


{'C': 2, 'H': 6}
[[0, 2], [0, 6]]
{'O': 2}
[[1, 2]]
[array([6., 0., 0.]), array([0., 2., 0.])]


In [ ]:
from chemtools import molarweight

class Compound:
    def __init__(self, formula: str, density:str=None, meltingpoint:str=None, boilingpoint:str=None) -> None:
        self.formula = formula
        self.weight = molarweight(formula)
        self.density = density
        self.meltingpoint = meltingpoint
        self.boilingpoint = boilingpoint

    @property
    def density(self):
        return self._density
    
    @density.setter
    def density(self, data):
        if data == None:
            self._density = None
            return
        try:
            value, unit = data.split()
            value = float(value)
            conversion = {
                "kg/m3": 1,
                "g/cm3": 1000,
                "kg/L": 1000
            }
            if not unit in conversion:
                raise ValueError(f"Unit: {unit} not found in database")
            
            self._density = value * conversion[unit]
        except (ValueError, AttributeError):
            raise ValueError(f"Input should be a value(float) follow by a unit(str)")
    
    @property
    def meltingpoint(self):
        return self._meltingpoint
    
    @meltingpoint.setter
    def meltingpoint(self, data):
        if data == None:
            self._meltingpoint = None
            return
        try:
            value, unit = data.split()
            value = float(value)
            conversion = {
                "K": 0,
                "C": 273.15
            }
            if not unit in conversion:
                raise ValueError(f"Unit: {unit} not found in database")
            
            self._meltingpoint = value + conversion[unit]
        except (ValueError, AttributeError):
            raise ValueError(f"Input should be a value(float) follow by a unit(str)")
    
    @property
    def boilingpoint(self):
        return self._boilingpoint
    
    @boilingpoint.setter
    def boilingpoint(self, data):
        if data == None:
            self._boilingpoint = None
            return
        try:
            value, unit = data.split()
            value = float(value)
            conversion = {
                "K": 0,
                "C": 273.15
            }
            if not unit in conversion:
                raise ValueError(f"Unit: {unit} not found in database")
            
            self._boilingpoint = value + conversion[unit]
        except (ValueError, AttributeError):
            raise ValueError(f"Input should be a value(float) follow by a unit(str)")        

    def __str__(self) -> str:
        result = f'Compound: {self.formula} ({self.weight} g/mol)'
        if self.density:
            result += f"\ndensity: {self.density} kg/m^3"
        if self._meltingpoint:
            result += f"\nmelting point: {self.meltingpoint} K"
        if self._boilingpoint: 
            result += f"\nboiling point: {self.boilingpoint} K"
        return result

Compound: H2SO4 (98.082 g/mol)
density: 1830.2 kg/m^3
melting point: 283.46 K
boiling point: 610.15 K
Compound: NaCl (58.4397693 g/mol)


In [50]:
class Test:
    def __init__(self, value=None):
        self.value = value

    @property
    def value(self):
        return self._value
    
    @value.setter
    def value(self, data):
        if data == None:
            self._value = None
            return
        try:
            value, unit = data.split()
            value = float(value)
            conversion = {"kg/m3": 1, "g/cm3": 1000, "kg/L": 1000}

            if not unit in conversion:
                raise ValueError(f"Unit: {unit} not in database")
            
            self._value = value * conversion[unit]
        except (ValueError, AttributeError):
            raise ValueError("Input should be float follow by unit")

test1 = Test("1 g/cm3")
print(test1.value)

1000.0


In [ ]:

class Mixture:
    def __init__(self, volume: float, solvent:Compound=Compound("H2O", 997, 273, 373)) -> None:
        self.volume = volume
        self.solvent = solvent
        self.__density = solvent.density
        self._contents = dict()
    
    @property
    def contents(self):
        if dict():
            return None
        else:
            return f"Mixture contains:\n{", ".join(f"{k.formula} at {v}M" for k, v in self._contents.items())}"

    def add(self, compound: Compound, concentration: float) -> None:
        if type(compound) == Compound and isinstance(concentration, (int, float)):
            self._contents[compound] = concentration
        else:
            raise ValueError("Incorrect inputtype")
        


In [9]:
from chemtools import validate_molecule

print(validate_molecule("Fe"))

True
